/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin/_authenticated'
import { Route as AdminPublicRouteImport } from './routes/admin/_public'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin/_authenticated/index'
import { Route as AdminAuthenticatedNodesRouteImport } from './routes/admin/_authenticated/nodes'
import { Route as AdminAuthenticatedUsersRouteImport } from './routes/admin/_authenticated/users'
import { Route as AdminPublicLoginRouteImport } from './routes/admin/_public/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublicRoute = AdminPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedNodesRoute = AdminAuthenticatedNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedUsersRoute = AdminAuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminPublicLoginRoute = AdminPublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminPublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/nodes': typeof AdminAuthenticatedNodesRoute
  '/admin/users': typeof AdminAuthenticatedUsersRoute
  '/admin/login': typeof AdminPublicLoginRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/admin/nodes': typeof AdminAuthenticatedNodesRoute
  '/admin/users': typeof AdminAuthenticatedUsersRoute
  '/admin/login': typeof AdminPublicLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/_public': typeof AdminPublicRouteWithChildren
  '/admin/_authenticated/nodes': typeof AdminAuthenticatedNodesRoute
  '/admin/_authenticated/users': typeof AdminAuthenticatedUsersRoute
  '/admin/_public/login': typeof AdminPublicLoginRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/nodes'
    | '/admin/users'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/admin/nodes' | '/admin/users' | '/admin/login'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/_authenticated'
    | '/admin/_public'
    | '/admin/_authenticated/nodes'
    | '/admin/_authenticated/users'
    | '/admin/_public/login'
    | '/admin/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_public': {
      id: '/admin/_public'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminPublicRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/nodes': {
      id: '/admin/_authenticated/nodes'
      path: '/nodes'
      fullPath: '/admin/nodes'
      preLoaderRoute: typeof AdminAuthenticatedNodesRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/users': {
      id: '/admin/_authenticated/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthenticatedUsersRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_public/login': {
      id: '/admin/_public/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminPublicLoginRouteImport
      parentRoute: typeof AdminPublicRoute
    }
  }
}

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedNodesRoute: typeof AdminAuthenticatedNodesRoute
  AdminAuthenticatedUsersRoute: typeof AdminAuthenticatedUsersRoute
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedNodesRoute: AdminAuthenticatedNodesRoute,
  AdminAuthenticatedUsersRoute: AdminAuthenticatedUsersRoute,
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

interface AdminPublicRouteChildren {
  AdminPublicLoginRoute: typeof AdminPublicLoginRoute
}

const AdminPublicRouteChildren: AdminPublicRouteChildren = {
  AdminPublicLoginRoute: AdminPublicLoginRoute,
}

const AdminPublicRouteWithChildren = AdminPublicRoute._addFileChildren(
  AdminPublicRouteChildren,
)

interface AdminRouteChildren {
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminPublicRoute: typeof AdminPublicRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminPublicRoute: AdminPublicRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
