import { useAtomSet, useAtomValue } from "@effect/atom-react"
import { ConfigureUgcProgram, type UgcProgramConfiguration, type UgcWorkspace } from "@proxus/shared/ugc-management"
import * as AsyncResult from "effect/unstable/reactivity/AsyncResult"
import { type FormEvent, useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { adminUgcCommandAction } from "./state.js"
import { programConfigurationFromFormData } from "./program-configuration.js"

const fallback = {
  trial: { durationDays: 14, warmingDays: 2, requiredVideoCount: 8, maxVideosPerDay: 2, minVideosPerWeek: 1, formats: ["testimonial", "review", "routine"], requiredPlatforms: ["tiktok", "instagram"] as const, completionCompensationCents: 7_200, currency: "EUR" as const },
  contractPolicy: { contentRetentionMonths: 3, creatorNoticeDays: 5, paidMediaRightsAmountCents: 3_000, paidMediaRightsDurationMonths: 3, exclusivityRequired: true },
  managerIncentives: { fixedPercentBasisPoints: 500, viewsBonusPercentBasisPoints: 500, rankingBonusPercentBasisPoints: 500, referralBonusPercentBasisPoints: 0, manualAdjustmentPercentBasisPoints: 0, outboundTrialPassBonusCents: 2_000 },
  historyRetentionDays: 90,
}

const percent = (value: number) => value / 100
const amount = (value: number) => value / 100

export function ProgramConfiguration({ workspace }: { readonly workspace: UgcWorkspace }) {
  const [market, setMarket] = useState(workspace.programConfigurations[0]?.market ?? "ES")
  const configuration = workspace.programConfigurations.find((item) => item.market === market)
  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]"><ProgramForm key={`${market}-${configuration?.version ?? 0}`} market={market} configuration={configuration} onMarketChange={setMarket} /><Card><CardHeader><CardTitle>Mercados configurados</CardTitle><CardDescription>Cada cambio crea una nueva versión. Los trials y campañas ya iniciados conservan su snapshot.</CardDescription></CardHeader><CardContent className="space-y-3">{workspace.programConfigurations.length === 0 ? <p className="text-sm text-muted-foreground">Aún se usan los valores iniciales del programa.</p> : workspace.programConfigurations.map((item) => <button type="button" key={item.market} onClick={() => setMarket(item.market)} className="flex w-full items-center justify-between rounded-xl border p-4 text-left"><span className="font-semibold">{item.market}</span><span className="text-xs text-muted-foreground">versión {item.version}</span></button>)}</CardContent></Card></div>
}

function ProgramForm({ market, configuration, onMarketChange }: { readonly market: string; readonly configuration: UgcProgramConfiguration | undefined; readonly onMarketChange: (market: string) => void }) {
  const [step, setStep] = useState(0)
  const run = useAtomSet(adminUgcCommandAction)
  const mutation = useAtomValue(adminUgcCommandAction)
  const waiting = AsyncResult.isWaiting(mutation)
  const current = configuration?.data ?? fallback
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    run(new ConfigureUgcProgram({
      market: String(data.get("market")).toUpperCase(),
      data: programConfigurationFromFormData(data),
    }))
  }
  return <Card><CardHeader><CardTitle>Configuración general UGC</CardTitle><CardDescription>Mercado {market} · paso {step + 1} de 3. Se aplicará a nuevos trials y se copiará en nuevas campañas.</CardDescription><div className="grid grid-cols-3 gap-2 pt-2" aria-label={`Paso ${step + 1} de 3`}>{[0, 1, 2].map((item) => <span key={item} className={`h-1.5 rounded-full ${item <= step ? "bg-primary" : "bg-muted"}`} />)}</div></CardHeader><CardContent><form className="grid gap-5" onSubmit={submit}>
    <fieldset className="grid gap-4" hidden={step !== 0}><legend className="mb-3 font-semibold">Trial y conservación del histórico</legend><div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-1 text-sm">Mercado<Input name="market" maxLength={2} value={market} onChange={(event) => onMarketChange(event.currentTarget.value.toUpperCase())} required /></label><label className="grid gap-1 text-sm">Moneda<select name="currency" defaultValue={current.trial.currency} className="h-9 rounded-md border bg-background px-3"><option>EUR</option><option>USD</option></select></label><label className="grid gap-1 text-sm">Compensación<Input name="trialCompensation" type="number" min="0" step="0.01" defaultValue={amount(current.trial.completionCompensationCents)} required /></label></div><div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-1 text-sm">Días de calentamiento<Input name="warmingDays" type="number" min="0" defaultValue={current.trial.warmingDays} required /></label><label className="grid gap-1 text-sm">Días de publicación<Input name="durationDays" type="number" min="1" defaultValue={current.trial.durationDays} required /></label><label className="grid gap-1 text-sm">Vídeos requeridos<Input name="requiredVideoCount" type="number" min="1" defaultValue={current.trial.requiredVideoCount} required /></label></div><div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-1 text-sm">Máximo diario<Input name="maxVideosPerDay" type="number" min="1" defaultValue={current.trial.maxVideosPerDay} required /></label><label className="grid gap-1 text-sm">Mínimo semanal<Input name="minVideosPerWeek" type="number" min="1" defaultValue={current.trial.minVideosPerWeek} required /></label><label className="grid gap-1 text-sm">Histórico visible (días)<Input name="historyRetentionDays" type="number" min="1" defaultValue={current.historyRetentionDays} required /></label></div><label className="grid gap-1 text-sm">Formatos permitidos<Input name="formats" defaultValue={current.trial.formats.join(", ")} required /></label><p className="text-xs text-muted-foreground">TikTok e Instagram son obligatorios y el trial solo se paga si se completan todos los vídeos validados.</p></fieldset>
    <fieldset className="grid gap-4" hidden={step !== 1}><legend className="mb-3 font-semibold">Condiciones contractuales</legend><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">Contenido público (meses)<Input name="contentRetentionMonths" type="number" min="1" defaultValue={current.contractPolicy.contentRetentionMonths} required /></label><label className="grid gap-1 text-sm">Preaviso del creador (días)<Input name="creatorNoticeDays" type="number" min="1" defaultValue={current.contractPolicy.creatorNoticeDays} required /></label><label className="grid gap-1 text-sm">Derechos paid media<Input name="paidMediaRightsAmount" type="number" min="0" step="0.01" defaultValue={amount(current.contractPolicy.paidMediaRightsAmountCents)} required /></label><label className="grid gap-1 text-sm">Duración paid media (meses)<Input name="paidMediaRightsDurationMonths" type="number" min="1" defaultValue={current.contractPolicy.paidMediaRightsDurationMonths} required /></label></div><label className="flex items-center gap-2 text-sm"><input name="exclusivityRequired" type="checkbox" defaultChecked={current.contractPolicy.exclusivityRequired} /> Exigir exclusividad durante la colaboración</label><p className="text-xs text-muted-foreground">Cambiar estos campos, la compensación, el objetivo, formatos, plataformas o bonus exigirá una nueva firma.</p></fieldset>
    <fieldset className="grid gap-4" hidden={step !== 2}><legend className="mb-3 font-semibold">Incentivos de managers</legend><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">% sobre fijo<Input name="fixedPercent" type="number" min="0" max="100" step="0.01" defaultValue={percent(current.managerIncentives.fixedPercentBasisPoints)} required /></label><label className="grid gap-1 text-sm">% sobre bonus de views<Input name="viewsPercent" type="number" min="0" max="100" step="0.01" defaultValue={percent(current.managerIncentives.viewsBonusPercentBasisPoints)} required /></label><label className="grid gap-1 text-sm">% sobre bonus de ranking<Input name="rankingPercent" type="number" min="0" max="100" step="0.01" defaultValue={percent(current.managerIncentives.rankingBonusPercentBasisPoints)} required /></label><label className="grid gap-1 text-sm">% sobre referidos<Input name="referralPercent" type="number" min="0" max="100" step="0.01" defaultValue={percent(current.managerIncentives.referralBonusPercentBasisPoints)} required /></label><label className="grid gap-1 text-sm">% sobre ajustes manuales<Input name="adjustmentPercent" type="number" min="0" max="100" step="0.01" defaultValue={percent(current.managerIncentives.manualAdjustmentPercentBasisPoints)} required /></label><label className="grid gap-1 text-sm">Bonus lead outbound que supera trial<Input name="outboundTrialPassBonus" type="number" min="0" step="0.01" defaultValue={amount(current.managerIncentives.outboundTrialPassBonusCents)} required /></label></div><p className="text-xs text-muted-foreground">Las campañas guardan esta política al crearse; los cambios futuros no recalculan pagos anteriores.</p></fieldset>
    <div className="flex justify-between gap-3"><Button type="button" variant="outline" disabled={step === 0} onClick={() => setStep((currentStep) => Math.max(0, currentStep - 1))}>Anterior</Button>{step < 2 ? <Button type="button" onClick={() => setStep((currentStep) => Math.min(2, currentStep + 1))}>Siguiente</Button> : <Button disabled={waiting}>Guardar versión</Button>}</div>
  </form></CardContent></Card>
}
