import { describe, expect, test } from "vitest"
import { assertPrivateMember, cloudBuildSourceViewerGrant, foundationApiNames, previewRoles, productionRoles, stateBackendPrincipals } from "./components/foundation.ts"
import { FoundationConfigError, readFoundationConfig } from "./foundation-config.ts"
const valid: NodeJS.ProcessEnv = { GCP_PROJECT_ID: "proxus-v2", GCP_PROJECT_NUMBER: "123456", GCP_PROJECT_DISPLAY_NAME: "Proxus v2", GCP_PROJECT_PARENT_TYPE: "organization", GCP_PROJECT_PARENT_ID: "123", GCP_REGION: "europe-southwest1", GITHUB_REPOSITORY: "owner/repo", ALCHEMY_STATE_BUCKET: "state", ALCHEMY_STATE_KMS_KEY: "projects/p/locations/l/keyRings/r/cryptoKeys/k", GCP_FOUNDATION_DEPLOYER_PRINCIPAL: "serviceAccount:foundation-deployer@proxus-v2.iam.gserviceaccount.com", ALCHEMY_ADOPT_EXISTING: "false", ALCHEMY_STACK_NAME: "foundation", ALCHEMY_STAGE: "foundation", ALCHEMY_LEASE_OWNER: "ci", ALCHEMY_LEASE_ID: "lease", ALCHEMY_LEASE_GENERATION: "1", ALCHEMY_LEASE_EXPIRES_AT: "9999999999999" }
describe("foundation config and offline security graph", () => {
  test("parses typed live-state configuration and requires explicit adoption", () => { expect(readFoundationConfig(valid)).toMatchObject({ project: "proxus-v2", projectNumber: "123456", cloudBuildSourceBucket: "proxus-v2_cloudbuild", cloudBuildSourceBucketLocation: "US", adoptExisting: false, lease: { stack: "foundation" } }); expect(() => readFoundationConfig({ ...valid, ALCHEMY_ADOPT_EXISTING: undefined })).toThrow(FoundationConfigError) })
  test("allows the exact Cloud Build source bucket to be overridden", () => { expect(readFoundationConfig({ ...valid, GCP_CLOUD_BUILD_SOURCE_BUCKET: "existing-source", GCP_CLOUD_BUILD_SOURCE_BUCKET_LOCATION: "EU" })).toMatchObject({ cloudBuildSourceBucket: "existing-source", cloudBuildSourceBucketLocation: "EU" }) })
  test("grants preview only the additional API and Cloud SQL administration needed by its graph", () => { expect(foundationApiNames).toHaveLength(13); expect(new Set(foundationApiNames).size).toBe(13); expect(productionRoles).toContain("roles/storage.admin"); expect(previewRoles).toContain("roles/serviceusage.serviceUsageAdmin"); expect(previewRoles).toContain("roles/cloudsql.admin"); expect(previewRoles).not.toContain("roles/storage.admin"); expect(previewRoles).not.toContain("roles/owner") })
  test("grants only bucket-level source object viewing to the Cloud Build executor", () => { expect(cloudBuildSourceViewerGrant(readFoundationConfig(valid))).toEqual({ bucket: "proxus-v2_cloudbuild", role: "roles/storage.objectViewer", member: "serviceAccount:proxus-cloud-build@proxus-v2.iam.gserviceaccount.com" }); expect([...productionRoles, ...previewRoles]).not.toContain("roles/storage.objectViewer") })
  test("grants the additive state backend graph to exactly the three private deployers", () => { expect(stateBackendPrincipals(readFoundationConfig(valid))).toEqual([["Foundation", "serviceAccount:foundation-deployer@proxus-v2.iam.gserviceaccount.com"], ["Production", "serviceAccount:proxus-production-deployer@proxus-v2.iam.gserviceaccount.com"], ["Preview", "serviceAccount:proxus-preview-deployer@proxus-v2.iam.gserviceaccount.com"]]); expect(() => assertPrivateMember("allUsers")).toThrow(); expect(() => assertPrivateMember("allAuthenticatedUsers")).toThrow() })
  test("pins repository syntax, foundation stack and a private foundation deployer", () => { expect(() => readFoundationConfig({ ...valid, GITHUB_REPOSITORY: "repo" })).toThrow(FoundationConfigError); expect(() => readFoundationConfig({ ...valid, ALCHEMY_STACK_NAME: "preview" })).toThrow(FoundationConfigError); expect(() => readFoundationConfig({ ...valid, GCP_FOUNDATION_DEPLOYER_PRINCIPAL: "allUsers" })).toThrow(FoundationConfigError); expect(readFoundationConfig(valid).foundationDeployerPrincipal).toContain("serviceAccount:") })
})
