/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicPasswordRecoveryRouteImport } from './routes/_public/password-recovery'
import { Route as PublicPasswordRecoveryIndexRouteImport } from './routes/_public/password-recovery/index'
import { Route as PublicPasswordRecoveryCodeRouteImport } from './routes/_public/password-recovery/code'
import { Route as PublicPasswordRecoveryDoneRouteImport } from './routes/_public/password-recovery/done'
import { Route as PublicPasswordRecoveryNewPasswordRouteImport } from './routes/_public/password-recovery/new-password'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPasswordRecoveryRoute = PublicPasswordRecoveryRouteImport.update({
  id: '/password-recovery',
  path: '/password-recovery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPasswordRecoveryIndexRoute =
  PublicPasswordRecoveryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicPasswordRecoveryRoute,
  } as any)
const PublicPasswordRecoveryCodeRoute =
  PublicPasswordRecoveryCodeRouteImport.update({
    id: '/code',
    path: '/code',
    getParentRoute: () => PublicPasswordRecoveryRoute,
  } as any)
const PublicPasswordRecoveryDoneRoute =
  PublicPasswordRecoveryDoneRouteImport.update({
    id: '/done',
    path: '/done',
    getParentRoute: () => PublicPasswordRecoveryRoute,
  } as any)
const PublicPasswordRecoveryNewPasswordRoute =
  PublicPasswordRecoveryNewPasswordRouteImport.update({
    id: '/new-password',
    path: '/new-password',
    getParentRoute: () => PublicPasswordRecoveryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/app': typeof AuthenticatedAppRoute
  '/login': typeof PublicLoginRoute
  '/password-recovery': typeof PublicPasswordRecoveryRouteWithChildren
  '/password-recovery/code': typeof PublicPasswordRecoveryCodeRoute
  '/password-recovery/done': typeof PublicPasswordRecoveryDoneRoute
  '/password-recovery/new-password': typeof PublicPasswordRecoveryNewPasswordRoute
  '/password-recovery/': typeof PublicPasswordRecoveryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/app': typeof AuthenticatedAppRoute
  '/login': typeof PublicLoginRoute
  '/password-recovery/code': typeof PublicPasswordRecoveryCodeRoute
  '/password-recovery/done': typeof PublicPasswordRecoveryDoneRoute
  '/password-recovery/new-password': typeof PublicPasswordRecoveryNewPasswordRoute
  '/password-recovery': typeof PublicPasswordRecoveryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/password-recovery': typeof PublicPasswordRecoveryRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_public/password-recovery/code': typeof PublicPasswordRecoveryCodeRoute
  '/_public/password-recovery/done': typeof PublicPasswordRecoveryDoneRoute
  '/_public/password-recovery/new-password': typeof PublicPasswordRecoveryNewPasswordRoute
  '/_public/password-recovery/': typeof PublicPasswordRecoveryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/password-recovery'
    | '/password-recovery/code'
    | '/password-recovery/done'
    | '/password-recovery/new-password'
    | '/password-recovery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/password-recovery/code'
    | '/password-recovery/done'
    | '/password-recovery/new-password'
    | '/password-recovery'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/app'
    | '/_public/login'
    | '/_public/password-recovery'
    | '/_public/'
    | '/_public/password-recovery/code'
    | '/_public/password-recovery/done'
    | '/_public/password-recovery/new-password'
    | '/_public/password-recovery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/password-recovery': {
      id: '/_public/password-recovery'
      path: '/password-recovery'
      fullPath: '/password-recovery'
      preLoaderRoute: typeof PublicPasswordRecoveryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/password-recovery/': {
      id: '/_public/password-recovery/'
      path: '/'
      fullPath: '/password-recovery/'
      preLoaderRoute: typeof PublicPasswordRecoveryIndexRouteImport
      parentRoute: typeof PublicPasswordRecoveryRoute
    }
    '/_public/password-recovery/code': {
      id: '/_public/password-recovery/code'
      path: '/code'
      fullPath: '/password-recovery/code'
      preLoaderRoute: typeof PublicPasswordRecoveryCodeRouteImport
      parentRoute: typeof PublicPasswordRecoveryRoute
    }
    '/_public/password-recovery/done': {
      id: '/_public/password-recovery/done'
      path: '/done'
      fullPath: '/password-recovery/done'
      preLoaderRoute: typeof PublicPasswordRecoveryDoneRouteImport
      parentRoute: typeof PublicPasswordRecoveryRoute
    }
    '/_public/password-recovery/new-password': {
      id: '/_public/password-recovery/new-password'
      path: '/new-password'
      fullPath: '/password-recovery/new-password'
      preLoaderRoute: typeof PublicPasswordRecoveryNewPasswordRouteImport
      parentRoute: typeof PublicPasswordRecoveryRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicPasswordRecoveryRouteChildren {
  PublicPasswordRecoveryCodeRoute: typeof PublicPasswordRecoveryCodeRoute
  PublicPasswordRecoveryDoneRoute: typeof PublicPasswordRecoveryDoneRoute
  PublicPasswordRecoveryNewPasswordRoute: typeof PublicPasswordRecoveryNewPasswordRoute
  PublicPasswordRecoveryIndexRoute: typeof PublicPasswordRecoveryIndexRoute
}

const PublicPasswordRecoveryRouteChildren: PublicPasswordRecoveryRouteChildren =
  {
    PublicPasswordRecoveryCodeRoute: PublicPasswordRecoveryCodeRoute,
    PublicPasswordRecoveryDoneRoute: PublicPasswordRecoveryDoneRoute,
    PublicPasswordRecoveryNewPasswordRoute:
      PublicPasswordRecoveryNewPasswordRoute,
    PublicPasswordRecoveryIndexRoute: PublicPasswordRecoveryIndexRoute,
  }

const PublicPasswordRecoveryRouteWithChildren =
  PublicPasswordRecoveryRoute._addFileChildren(
    PublicPasswordRecoveryRouteChildren,
  )

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicPasswordRecoveryRoute: typeof PublicPasswordRecoveryRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicPasswordRecoveryRoute: PublicPasswordRecoveryRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
