/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UgcRouteImport } from './routes/ugc'
import { Route as UgcAuthenticatedRouteImport } from './routes/ugc/_authenticated'
import { Route as UgcPublicRouteImport } from './routes/ugc/_public'
import { Route as UgcAuthenticatedIndexRouteImport } from './routes/ugc/_authenticated/index'
import { Route as UgcAuthenticatedManagerRouteImport } from './routes/ugc/_authenticated/manager'
import { Route as UgcAuthenticatedPaymentsRouteImport } from './routes/ugc/_authenticated/payments'
import { Route as UgcAuthenticatedProfileRouteImport } from './routes/ugc/_authenticated/profile'
import { Route as UgcAuthenticatedVideosRouteImport } from './routes/ugc/_authenticated/videos'
import { Route as UgcPublicLoginRouteImport } from './routes/ugc/_public/login'

const UgcRoute = UgcRouteImport.update({
  id: '/ugc',
  path: '/ugc',
  getParentRoute: () => rootRouteImport,
} as any)
const UgcAuthenticatedRoute = UgcAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => UgcRoute,
} as any)
const UgcPublicRoute = UgcPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => UgcRoute,
} as any)
const UgcAuthenticatedIndexRoute = UgcAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UgcAuthenticatedRoute,
} as any)
const UgcAuthenticatedManagerRoute = UgcAuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => UgcAuthenticatedRoute,
} as any)
const UgcAuthenticatedPaymentsRoute =
  UgcAuthenticatedPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => UgcAuthenticatedRoute,
  } as any)
const UgcAuthenticatedProfileRoute = UgcAuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UgcAuthenticatedRoute,
} as any)
const UgcAuthenticatedVideosRoute = UgcAuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => UgcAuthenticatedRoute,
} as any)
const UgcPublicLoginRoute = UgcPublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UgcPublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/ugc': typeof UgcRouteWithChildren
  '/ugc/manager': typeof UgcAuthenticatedManagerRoute
  '/ugc/payments': typeof UgcAuthenticatedPaymentsRoute
  '/ugc/profile': typeof UgcAuthenticatedProfileRoute
  '/ugc/videos': typeof UgcAuthenticatedVideosRoute
  '/ugc/login': typeof UgcPublicLoginRoute
  '/ugc/': typeof UgcAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/ugc': typeof UgcAuthenticatedIndexRoute
  '/ugc/manager': typeof UgcAuthenticatedManagerRoute
  '/ugc/payments': typeof UgcAuthenticatedPaymentsRoute
  '/ugc/profile': typeof UgcAuthenticatedProfileRoute
  '/ugc/videos': typeof UgcAuthenticatedVideosRoute
  '/ugc/login': typeof UgcPublicLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/ugc': typeof UgcRouteWithChildren
  '/ugc/_authenticated': typeof UgcAuthenticatedRouteWithChildren
  '/ugc/_public': typeof UgcPublicRouteWithChildren
  '/ugc/_authenticated/manager': typeof UgcAuthenticatedManagerRoute
  '/ugc/_authenticated/payments': typeof UgcAuthenticatedPaymentsRoute
  '/ugc/_authenticated/profile': typeof UgcAuthenticatedProfileRoute
  '/ugc/_authenticated/videos': typeof UgcAuthenticatedVideosRoute
  '/ugc/_public/login': typeof UgcPublicLoginRoute
  '/ugc/_authenticated/': typeof UgcAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ugc'
    | '/ugc/manager'
    | '/ugc/payments'
    | '/ugc/profile'
    | '/ugc/videos'
    | '/ugc/login'
    | '/ugc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ugc'
    | '/ugc/manager'
    | '/ugc/payments'
    | '/ugc/profile'
    | '/ugc/videos'
    | '/ugc/login'
  id:
    | '__root__'
    | '/ugc'
    | '/ugc/_authenticated'
    | '/ugc/_public'
    | '/ugc/_authenticated/manager'
    | '/ugc/_authenticated/payments'
    | '/ugc/_authenticated/profile'
    | '/ugc/_authenticated/videos'
    | '/ugc/_public/login'
    | '/ugc/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UgcRoute: typeof UgcRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ugc': {
      id: '/ugc'
      path: '/ugc'
      fullPath: '/ugc'
      preLoaderRoute: typeof UgcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ugc/_authenticated': {
      id: '/ugc/_authenticated'
      path: ''
      fullPath: '/ugc'
      preLoaderRoute: typeof UgcAuthenticatedRouteImport
      parentRoute: typeof UgcRoute
    }
    '/ugc/_public': {
      id: '/ugc/_public'
      path: ''
      fullPath: '/ugc'
      preLoaderRoute: typeof UgcPublicRouteImport
      parentRoute: typeof UgcRoute
    }
    '/ugc/_authenticated/': {
      id: '/ugc/_authenticated/'
      path: '/'
      fullPath: '/ugc/'
      preLoaderRoute: typeof UgcAuthenticatedIndexRouteImport
      parentRoute: typeof UgcAuthenticatedRoute
    }
    '/ugc/_authenticated/manager': {
      id: '/ugc/_authenticated/manager'
      path: '/manager'
      fullPath: '/ugc/manager'
      preLoaderRoute: typeof UgcAuthenticatedManagerRouteImport
      parentRoute: typeof UgcAuthenticatedRoute
    }
    '/ugc/_authenticated/payments': {
      id: '/ugc/_authenticated/payments'
      path: '/payments'
      fullPath: '/ugc/payments'
      preLoaderRoute: typeof UgcAuthenticatedPaymentsRouteImport
      parentRoute: typeof UgcAuthenticatedRoute
    }
    '/ugc/_authenticated/profile': {
      id: '/ugc/_authenticated/profile'
      path: '/profile'
      fullPath: '/ugc/profile'
      preLoaderRoute: typeof UgcAuthenticatedProfileRouteImport
      parentRoute: typeof UgcAuthenticatedRoute
    }
    '/ugc/_authenticated/videos': {
      id: '/ugc/_authenticated/videos'
      path: '/videos'
      fullPath: '/ugc/videos'
      preLoaderRoute: typeof UgcAuthenticatedVideosRouteImport
      parentRoute: typeof UgcAuthenticatedRoute
    }
    '/ugc/_public/login': {
      id: '/ugc/_public/login'
      path: '/login'
      fullPath: '/ugc/login'
      preLoaderRoute: typeof UgcPublicLoginRouteImport
      parentRoute: typeof UgcPublicRoute
    }
  }
}

interface UgcAuthenticatedRouteChildren {
  UgcAuthenticatedManagerRoute: typeof UgcAuthenticatedManagerRoute
  UgcAuthenticatedPaymentsRoute: typeof UgcAuthenticatedPaymentsRoute
  UgcAuthenticatedProfileRoute: typeof UgcAuthenticatedProfileRoute
  UgcAuthenticatedVideosRoute: typeof UgcAuthenticatedVideosRoute
  UgcAuthenticatedIndexRoute: typeof UgcAuthenticatedIndexRoute
}

const UgcAuthenticatedRouteChildren: UgcAuthenticatedRouteChildren = {
  UgcAuthenticatedManagerRoute: UgcAuthenticatedManagerRoute,
  UgcAuthenticatedPaymentsRoute: UgcAuthenticatedPaymentsRoute,
  UgcAuthenticatedProfileRoute: UgcAuthenticatedProfileRoute,
  UgcAuthenticatedVideosRoute: UgcAuthenticatedVideosRoute,
  UgcAuthenticatedIndexRoute: UgcAuthenticatedIndexRoute,
}

const UgcAuthenticatedRouteWithChildren =
  UgcAuthenticatedRoute._addFileChildren(UgcAuthenticatedRouteChildren)

interface UgcPublicRouteChildren {
  UgcPublicLoginRoute: typeof UgcPublicLoginRoute
}

const UgcPublicRouteChildren: UgcPublicRouteChildren = {
  UgcPublicLoginRoute: UgcPublicLoginRoute,
}

const UgcPublicRouteWithChildren = UgcPublicRoute._addFileChildren(
  UgcPublicRouteChildren,
)

interface UgcRouteChildren {
  UgcAuthenticatedRoute: typeof UgcAuthenticatedRouteWithChildren
  UgcPublicRoute: typeof UgcPublicRouteWithChildren
}

const UgcRouteChildren: UgcRouteChildren = {
  UgcAuthenticatedRoute: UgcAuthenticatedRouteWithChildren,
  UgcPublicRoute: UgcPublicRouteWithChildren,
}

const UgcRouteWithChildren = UgcRoute._addFileChildren(UgcRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  UgcRoute: UgcRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
