/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleAuthenticatedRouteImport } from './routes/$locale/_authenticated'
import { Route as LocalePublicRouteImport } from './routes/$locale/_public'
import { Route as LocaleAuthenticatedAppRouteImport } from './routes/$locale/_authenticated/app'
import { Route as LocalePublicIndexRouteImport } from './routes/$locale/_public/index'
import { Route as LocalePublicLoginRouteImport } from './routes/$locale/_public/login'
import { Route as LocalePublicPasswordRecoveryRouteImport } from './routes/$locale/_public/password-recovery'
import { Route as LocalePublicPasswordRecoveryIndexRouteImport } from './routes/$locale/_public/password-recovery/index'
import { Route as LocalePublicPasswordRecoveryCodeRouteImport } from './routes/$locale/_public/password-recovery/code'
import { Route as LocalePublicPasswordRecoveryDoneRouteImport } from './routes/$locale/_public/password-recovery/done'
import { Route as LocalePublicPasswordRecoveryNewPasswordRouteImport } from './routes/$locale/_public/password-recovery/new-password'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAuthenticatedRoute = LocaleAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePublicRoute = LocalePublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthenticatedAppRoute = LocaleAuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LocaleAuthenticatedRoute,
} as any)
const LocalePublicIndexRoute = LocalePublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocalePublicRoute,
} as any)
const LocalePublicLoginRoute = LocalePublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocalePublicRoute,
} as any)
const LocalePublicPasswordRecoveryRoute =
  LocalePublicPasswordRecoveryRouteImport.update({
    id: '/password-recovery',
    path: '/password-recovery',
    getParentRoute: () => LocalePublicRoute,
  } as any)
const LocalePublicPasswordRecoveryIndexRoute =
  LocalePublicPasswordRecoveryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocalePublicPasswordRecoveryRoute,
  } as any)
const LocalePublicPasswordRecoveryCodeRoute =
  LocalePublicPasswordRecoveryCodeRouteImport.update({
    id: '/code',
    path: '/code',
    getParentRoute: () => LocalePublicPasswordRecoveryRoute,
  } as any)
const LocalePublicPasswordRecoveryDoneRoute =
  LocalePublicPasswordRecoveryDoneRouteImport.update({
    id: '/done',
    path: '/done',
    getParentRoute: () => LocalePublicPasswordRecoveryRoute,
  } as any)
const LocalePublicPasswordRecoveryNewPasswordRoute =
  LocalePublicPasswordRecoveryNewPasswordRouteImport.update({
    id: '/new-password',
    path: '/new-password',
    getParentRoute: () => LocalePublicPasswordRecoveryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/app': typeof LocaleAuthenticatedAppRoute
  '/$locale/login': typeof LocalePublicLoginRoute
  '/$locale/password-recovery': typeof LocalePublicPasswordRecoveryRouteWithChildren
  '/$locale/': typeof LocalePublicIndexRoute
  '/$locale/password-recovery/code': typeof LocalePublicPasswordRecoveryCodeRoute
  '/$locale/password-recovery/done': typeof LocalePublicPasswordRecoveryDoneRoute
  '/$locale/password-recovery/new-password': typeof LocalePublicPasswordRecoveryNewPasswordRoute
  '/$locale/password-recovery/': typeof LocalePublicPasswordRecoveryIndexRoute
}
export interface FileRoutesByTo {
  '/$locale': typeof LocalePublicIndexRoute
  '/$locale/app': typeof LocaleAuthenticatedAppRoute
  '/$locale/login': typeof LocalePublicLoginRoute
  '/$locale/password-recovery/code': typeof LocalePublicPasswordRecoveryCodeRoute
  '/$locale/password-recovery/done': typeof LocalePublicPasswordRecoveryDoneRoute
  '/$locale/password-recovery/new-password': typeof LocalePublicPasswordRecoveryNewPasswordRoute
  '/$locale/password-recovery': typeof LocalePublicPasswordRecoveryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_authenticated': typeof LocaleAuthenticatedRouteWithChildren
  '/$locale/_public': typeof LocalePublicRouteWithChildren
  '/$locale/_authenticated/app': typeof LocaleAuthenticatedAppRoute
  '/$locale/_public/login': typeof LocalePublicLoginRoute
  '/$locale/_public/password-recovery': typeof LocalePublicPasswordRecoveryRouteWithChildren
  '/$locale/_public/': typeof LocalePublicIndexRoute
  '/$locale/_public/password-recovery/code': typeof LocalePublicPasswordRecoveryCodeRoute
  '/$locale/_public/password-recovery/done': typeof LocalePublicPasswordRecoveryDoneRoute
  '/$locale/_public/password-recovery/new-password': typeof LocalePublicPasswordRecoveryNewPasswordRoute
  '/$locale/_public/password-recovery/': typeof LocalePublicPasswordRecoveryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/$locale/app'
    | '/$locale/login'
    | '/$locale/password-recovery'
    | '/$locale/'
    | '/$locale/password-recovery/code'
    | '/$locale/password-recovery/done'
    | '/$locale/password-recovery/new-password'
    | '/$locale/password-recovery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale'
    | '/$locale/app'
    | '/$locale/login'
    | '/$locale/password-recovery/code'
    | '/$locale/password-recovery/done'
    | '/$locale/password-recovery/new-password'
    | '/$locale/password-recovery'
  id:
    | '__root__'
    | '/$locale'
    | '/$locale/_authenticated'
    | '/$locale/_public'
    | '/$locale/_authenticated/app'
    | '/$locale/_public/login'
    | '/$locale/_public/password-recovery'
    | '/$locale/_public/'
    | '/$locale/_public/password-recovery/code'
    | '/$locale/_public/password-recovery/done'
    | '/$locale/_public/password-recovery/new-password'
    | '/$locale/_public/password-recovery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_authenticated': {
      id: '/$locale/_authenticated'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthenticatedRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_public': {
      id: '/$locale/_public'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocalePublicRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_authenticated/app': {
      id: '/$locale/_authenticated/app'
      path: '/app'
      fullPath: '/$locale/app'
      preLoaderRoute: typeof LocaleAuthenticatedAppRouteImport
      parentRoute: typeof LocaleAuthenticatedRoute
    }
    '/$locale/_public/': {
      id: '/$locale/_public/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocalePublicIndexRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/login': {
      id: '/$locale/_public/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocalePublicLoginRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/password-recovery': {
      id: '/$locale/_public/password-recovery'
      path: '/password-recovery'
      fullPath: '/$locale/password-recovery'
      preLoaderRoute: typeof LocalePublicPasswordRecoveryRouteImport
      parentRoute: typeof LocalePublicRoute
    }
    '/$locale/_public/password-recovery/': {
      id: '/$locale/_public/password-recovery/'
      path: '/'
      fullPath: '/$locale/password-recovery/'
      preLoaderRoute: typeof LocalePublicPasswordRecoveryIndexRouteImport
      parentRoute: typeof LocalePublicPasswordRecoveryRoute
    }
    '/$locale/_public/password-recovery/code': {
      id: '/$locale/_public/password-recovery/code'
      path: '/code'
      fullPath: '/$locale/password-recovery/code'
      preLoaderRoute: typeof LocalePublicPasswordRecoveryCodeRouteImport
      parentRoute: typeof LocalePublicPasswordRecoveryRoute
    }
    '/$locale/_public/password-recovery/done': {
      id: '/$locale/_public/password-recovery/done'
      path: '/done'
      fullPath: '/$locale/password-recovery/done'
      preLoaderRoute: typeof LocalePublicPasswordRecoveryDoneRouteImport
      parentRoute: typeof LocalePublicPasswordRecoveryRoute
    }
    '/$locale/_public/password-recovery/new-password': {
      id: '/$locale/_public/password-recovery/new-password'
      path: '/new-password'
      fullPath: '/$locale/password-recovery/new-password'
      preLoaderRoute: typeof LocalePublicPasswordRecoveryNewPasswordRouteImport
      parentRoute: typeof LocalePublicPasswordRecoveryRoute
    }
  }
}

interface LocaleAuthenticatedRouteChildren {
  LocaleAuthenticatedAppRoute: typeof LocaleAuthenticatedAppRoute
}

const LocaleAuthenticatedRouteChildren: LocaleAuthenticatedRouteChildren = {
  LocaleAuthenticatedAppRoute: LocaleAuthenticatedAppRoute,
}

const LocaleAuthenticatedRouteWithChildren =
  LocaleAuthenticatedRoute._addFileChildren(LocaleAuthenticatedRouteChildren)

interface LocalePublicPasswordRecoveryRouteChildren {
  LocalePublicPasswordRecoveryCodeRoute: typeof LocalePublicPasswordRecoveryCodeRoute
  LocalePublicPasswordRecoveryDoneRoute: typeof LocalePublicPasswordRecoveryDoneRoute
  LocalePublicPasswordRecoveryNewPasswordRoute: typeof LocalePublicPasswordRecoveryNewPasswordRoute
  LocalePublicPasswordRecoveryIndexRoute: typeof LocalePublicPasswordRecoveryIndexRoute
}

const LocalePublicPasswordRecoveryRouteChildren: LocalePublicPasswordRecoveryRouteChildren =
  {
    LocalePublicPasswordRecoveryCodeRoute:
      LocalePublicPasswordRecoveryCodeRoute,
    LocalePublicPasswordRecoveryDoneRoute:
      LocalePublicPasswordRecoveryDoneRoute,
    LocalePublicPasswordRecoveryNewPasswordRoute:
      LocalePublicPasswordRecoveryNewPasswordRoute,
    LocalePublicPasswordRecoveryIndexRoute:
      LocalePublicPasswordRecoveryIndexRoute,
  }

const LocalePublicPasswordRecoveryRouteWithChildren =
  LocalePublicPasswordRecoveryRoute._addFileChildren(
    LocalePublicPasswordRecoveryRouteChildren,
  )

interface LocalePublicRouteChildren {
  LocalePublicLoginRoute: typeof LocalePublicLoginRoute
  LocalePublicPasswordRecoveryRoute: typeof LocalePublicPasswordRecoveryRouteWithChildren
  LocalePublicIndexRoute: typeof LocalePublicIndexRoute
}

const LocalePublicRouteChildren: LocalePublicRouteChildren = {
  LocalePublicLoginRoute: LocalePublicLoginRoute,
  LocalePublicPasswordRecoveryRoute:
    LocalePublicPasswordRecoveryRouteWithChildren,
  LocalePublicIndexRoute: LocalePublicIndexRoute,
}

const LocalePublicRouteWithChildren = LocalePublicRoute._addFileChildren(
  LocalePublicRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAuthenticatedRoute: typeof LocaleAuthenticatedRouteWithChildren
  LocalePublicRoute: typeof LocalePublicRouteWithChildren
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAuthenticatedRoute: LocaleAuthenticatedRouteWithChildren,
  LocalePublicRoute: LocalePublicRouteWithChildren,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
