import { Brain, File, Wrench } from "lucide-react"
import type { ComponentProps, ReactNode } from "react"
import { cn } from "../lib/cn.js"

export function Conversation({ className, ...props }: ComponentProps<"section">) { return <section className={cn("flex min-h-0 flex-1 flex-col", className)} {...props} /> }
export function ConversationEmptyState({ title = "Empieza una conversación", description = "Escribe un mensaje o adjunta contexto.", className, ...props }: ComponentProps<"div"> & { readonly title?: string; readonly description?: string }) { return <div className={cn("grid flex-1 place-items-center p-8 text-center", className)} {...props}><div><h2 className="font-medium">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div></div> }
export function Attachment({ name, meta, onRemove, className, ...props }: ComponentProps<"div"> & { readonly name: string; readonly meta?: string; readonly onRemove?: () => void }) { return <div className={cn("flex max-w-64 items-center gap-2 rounded-lg border bg-muted/40 p-2 text-xs", className)} {...props}><File className="size-4 shrink-0" /><span className="min-w-0 flex-1 truncate"><strong className="block truncate font-medium">{name}</strong>{meta && <span className="text-muted-foreground">{meta}</span>}</span>{onRemove && <button type="button" onClick={onRemove} aria-label={`Quitar ${name}`}>×</button>}</div> }
export function Reasoning({ children, className, ...props }: ComponentProps<"details">) { return <details className={cn("rounded-lg border p-3 text-sm", className)} {...props}><summary className="flex cursor-pointer items-center gap-2 font-medium"><Brain className="size-4" />Razonamiento</summary><div className="mt-2 text-muted-foreground">{children}</div></details> }
export function Tool({ name, status, children, className, ...props }: ComponentProps<"div"> & { readonly name: string; readonly status: string; readonly children?: ReactNode }) { return <div className={cn("rounded-lg border p-3 text-sm", className)} {...props}><div className="flex items-center gap-2 font-medium"><Wrench className="size-4" />{name}<span className="ml-auto text-xs text-muted-foreground">{status}</span></div>{children && <div className="mt-2 font-mono text-xs">{children}</div>}</div> }
