import type {
  CampaignSummary,
  CreatorHomePresentation,
  CreatorPayment,
  CreatorScenario,
  CreatorVideo,
} from "./types.js"

const campaign: CampaignSummary = {
  name: "GlowUp España",
  dates: "24 ago — 1 sept",
  tier: "Tier 2",
  group: "Equipo Violeta",
  manager: "Marta Gómez",
  formats: ["Rutina", "Antes y después", "Review"],
  compensation: "240 € base",
  bonus: "Hasta 160 € en bonus",
}

export const videos: ReadonlyArray<CreatorVideo> = [
  {
    id: "video-8",
    title: "Mi rutina de noche",
    context: "Campaña GlowUp",
    format: "Rutina",
    publishedAt: "29 ago 2026",
    status: "En revisión",
    tiktokUrl: "tiktok.com/@lucia/video/8",
    instagramUrl: "instagram.com/reel/glowup-8",
    tiktokViews: "12,8 mil",
    instagramViews: "5,6 mil",
    totalViews: "18,4 mil",
    reference: "GLW8",
    fixedAmount: "30 €",
    bonusAmount: "—",
    totalAmount: "30 €",
  },
  {
    id: "video-7",
    title: "Resultados después de 7 días",
    context: "Campaña GlowUp",
    format: "Antes y después",
    publishedAt: "28 ago 2026",
    status: "Aceptado",
    tiktokUrl: "tiktok.com/@lucia/video/7",
    instagramUrl: "instagram.com/reel/glowup-7",
    tiktokViews: "31,4 mil",
    instagramViews: "10,7 mil",
    totalViews: "42,1 mil",
    reference: "GLW7",
    fixedAmount: "30 €",
    bonusAmount: "+25 €",
    totalAmount: "55 €",
  },
  {
    id: "video-6",
    title: "Tres cosas que me sorprendieron",
    context: "Campaña GlowUp",
    format: "Review",
    publishedAt: "27 ago 2026",
    status: "Necesita cambios",
    tiktokUrl: "tiktok.com/@lucia/video/6",
    instagramUrl: "instagram.com/reel/glowup-6",
    tiktokViews: "7,1 mil",
    instagramViews: "2,7 mil",
    totalViews: "9,8 mil",
    reference: "Contenido propio",
    fixedAmount: "30 €",
    totalAmount: "30 €",
  },
  {
    id: "video-5",
    title: "Get ready with me",
    context: "Campaña GlowUp",
    format: "Rutina",
    publishedAt: "26 ago 2026",
    status: "Aceptado",
    tiktokUrl: "tiktok.com/@lucia/video/5",
    instagramUrl: "instagram.com/reel/glowup-5",
    tiktokViews: "22,2 mil",
    instagramViews: "9,4 mil",
    totalViews: "31,6 mil",
    reference: "GLW5",
    fixedAmount: "30 €",
    bonusAmount: "+15 €",
    totalAmount: "45 €",
  },
  {
    id: "video-4",
    title: "Probando el sérum por primera vez",
    context: "Trial",
    format: "Primera impresión",
    publishedAt: "12 ago 2026",
    status: "Bloqueado",
    tiktokUrl: "tiktok.com/@lucia/video/4",
    instagramUrl: "instagram.com/reel/trial-4",
    tiktokViews: "10,9 mil",
    instagramViews: "4,3 mil",
    totalViews: "15,2 mil",
    reference: "Contenido propio",
    fixedAmount: "—",
    totalAmount: "—",
  },
  {
    id: "video-3",
    title: "Rutina rápida antes de clase",
    context: "Trial",
    format: "Rutina",
    publishedAt: "11 ago 2026",
    status: "Bloqueado",
    tiktokUrl: "tiktok.com/@lucia/video/3",
    instagramUrl: "instagram.com/reel/trial-3",
    tiktokViews: "16,8 mil",
    instagramViews: "5,9 mil",
    totalViews: "22,7 mil",
    reference: "Contenido propio",
    fixedAmount: "—",
    totalAmount: "—",
  },
]

const pendingGlowUpPayment: CreatorPayment = {
  id: "payment-glowup",
  campaign: "GlowUp España",
  period: "Agosto 2026",
  amount: "325,00 €",
  status: "Pendiente",
  baseAmount: "240,00 €",
  bonusAmount: "85,00 €",
}

export const payments: ReadonlyArray<CreatorPayment> = [
  pendingGlowUpPayment,
  {
    id: "payment-summer",
    campaign: "Summer Skin",
    period: "Julio 2026",
    amount: "280,00 €",
    status: "Pagado",
    paidAt: "5 ago 2026",
    baseAmount: "220,00 €",
    bonusAmount: "60,00 €",
  },
]

const onboardingRequirements = [
  { id: "profile", label: "Completa tu perfil", completed: true },
  { id: "training", label: "Conoce cómo funciona Proxus", completed: true },
  { id: "tiktok", label: "Registra tu cuenta de TikTok", completed: true },
  {
    id: "contract",
    label: "Firma el acuerdo de colaboración",
    detail: "Solo te llevará un minuto",
    completed: false,
    current: true,
  },
  { id: "meeting", label: "Reserva tu reunión de bienvenida", completed: false },
] as const

const trialRequirements = [
  { id: "contract", label: "Acuerdo firmado", completed: true },
  { id: "account", label: "Cuenta de TikTok registrada", completed: true },
  {
    id: "warmup",
    label: "Completa el calentamiento de la cuenta",
    detail: "Día 1 de 2",
    completed: false,
    current: true,
  },
] as const

export const homePresentations = {
  applicationPending: {
    statusLabel: "Solicitud en revisión",
    tone: "neutral",
    title: "Ya tenemos tu solicitud",
    description:
      "Nuestro equipo está revisando tus datos. Te avisaremos por email en cuanto tengamos una respuesta.",
    meta: "Solicitud enviada el 18 de agosto",
    primaryAction: { label: "Revisar mis datos", kind: "navigate", target: "profile" },
  },
  applicationRejected: {
    statusLabel: "Solicitud no aceptada",
    tone: "negative",
    title: "Esta vez no podemos continuar",
    description:
      "Tu perfil no encaja con las campañas que tenemos disponibles ahora mismo. Podrás volver a solicitar acceso más adelante.",
    meta: "Decisión tomada el 20 de agosto",
    primaryAction: { label: "Consultar mis datos", kind: "navigate", target: "profile" },
    secondaryAction: { label: "Contactar con soporte", kind: "noop" },
  },
  onboarding: {
    statusLabel: "Onboarding",
    tone: "brand",
    title: "Prepara todo para empezar",
    description: "Completa estos pasos para poder reservar tu reunión de bienvenida.",
    progress: { value: 60, label: "3 de 5 pasos", detail: "Te quedan unos 5 minutos" },
    requirements: onboardingRequirements,
    primaryAction: { label: "Firmar acuerdo", kind: "noop" },
  },
  meetingPending: {
    statusLabel: "Último paso del onboarding",
    tone: "brand",
    title: "Reserva tu reunión de bienvenida",
    description:
      "Conocerás a una persona del equipo, resolveremos tus dudas y prepararemos tu periodo de prueba.",
    primaryAction: { label: "Elegir fecha y hora", kind: "meeting" },
    notice: {
      tone: "info",
      title: "30 minutos por videollamada",
      description: "Verás los horarios disponibles en tu zona horaria.",
    },
  },
  meetingScheduled: {
    statusLabel: "Reunión reservada",
    tone: "positive",
    title: "Nos vemos el lunes",
    description: "Te enviaremos un recordatorio antes de la reunión.",
    meeting: {
      date: "Lunes, 24 de agosto",
      time: "11:30",
      timezone: "Hora peninsular española",
      manager: "Marta Gómez",
      joinUrl: "#",
    },
    primaryAction: { label: "Entrar a la reunión", kind: "noop" },
    secondaryAction: { label: "Cambiar la reserva", kind: "meeting" },
  },
  meetingMissed: {
    statusLabel: "Reunión pendiente",
    tone: "warning",
    title: "No pudimos verte en la reunión",
    description: "Reserva una nueva fecha para continuar con tu acceso a Proxus.",
    primaryAction: { label: "Reservar otra reunión", kind: "meeting" },
    notice: {
      tone: "warning",
      title: "Esta fue tu primera ausencia",
      description: "Si vuelves a faltar sin avisar, tu solicitud podría cerrarse.",
    },
  },
  trialPreparation: {
    statusLabel: "Periodo de prueba",
    tone: "brand",
    title: "Tu prueba está a punto de empezar",
    description: "Completa los últimos preparativos antes de empezar a publicar.",
    progress: { value: 66, label: "2 de 3 pasos", detail: "Publicación disponible el 26 de agosto" },
    requirements: trialRequirements,
    primaryAction: { label: "Ver instrucciones", kind: "noop" },
  },
  trialWarming: {
    statusLabel: "Calentamiento · Día 1 de 2",
    tone: "brand",
    title: "Podrás publicar en 1 día",
    description:
      "Utiliza tu cuenta con normalidad durante el calentamiento. Todavía no publiques los vídeos de la prueba.",
    deadline: "Empiezas el miércoles 26 de agosto",
    progress: { value: 50, label: "1 de 2 días", detail: "La publicación se activará automáticamente" },
    primaryAction: { label: "Ver guía de calentamiento", kind: "noop" },
  },
  trialPublishing: {
    statusLabel: "Periodo de prueba activo",
    tone: "brand",
    title: "Publica 8 vídeos en 8 días",
    description: "Vas muy bien. Mantén el ritmo para completar la prueba antes del 3 de septiembre.",
    deadline: "5 días restantes",
    progress: { value: 50, label: "4 de 8 vídeos", detail: "El siguiente vídeo vence mañana" },
    performance: {
      tiktokViews: "57,8 mil",
      instagramViews: "18,4 mil",
      referrals: "3",
      fixedEarnings: "—",
      bonusEarnings: "—",
      estimatedEarnings: "Prueba",
      pendingVideos: 1,
    },
    recentVideos: videos.slice(2, 5),
    primaryAction: { label: "Subir un vídeo", kind: "upload" },
    secondaryAction: { label: "Ver todos", kind: "navigate", target: "videos" },
  },
  trialReview: {
    statusLabel: "Prueba en revisión",
    tone: "neutral",
    title: "Estamos revisando tus vídeos",
    description: "Has completado los 8 vídeos. Te avisaremos cuando el equipo termine la evaluación.",
    meta: "Prueba completada el 3 de septiembre",
    progress: { value: 100, label: "8 de 8 vídeos", detail: "No necesitas hacer nada más" },
    recentVideos: videos.slice(2, 5),
    primaryAction: { label: "Ver mis vídeos", kind: "navigate", target: "videos" },
  },
  trialNotPassed: {
    statusLabel: "Prueba finalizada",
    tone: "negative",
    title: "No has superado el periodo de prueba",
    description:
      "El equipo ha revisado tus vídeos y, por ahora, no podemos incorporarte a las campañas de Proxus.",
    meta: "Prueba evaluada el 5 de septiembre",
    recentVideos: videos.slice(2, 5),
    primaryAction: { label: "Revisar mis vídeos", kind: "navigate", target: "videos" },
    secondaryAction: { label: "Contactar con soporte", kind: "noop" },
  },
  waitingCampaign: {
    statusLabel: "Creadora aprobada",
    tone: "positive",
    title: "Ya formas parte de Proxus",
    description:
      "Te avisaremos cuando encontremos una campaña compatible con tu perfil, país y disponibilidad.",
    meta: "Tier actual · Tier 2",
    primaryAction: { label: "Actualizar disponibilidad", kind: "navigate", target: "profile" },
    notice: {
      tone: "success",
      title: "Periodo de prueba superado",
      description: "Tu perfil ya puede participar en nuevas campañas.",
    },
  },
  campaignScheduled: {
    statusLabel: "Próxima campaña",
    tone: "brand",
    title: "GlowUp empieza en 3 días",
    description: "Revisa los formatos y las reglas para tenerlo todo preparado.",
    deadline: "Empieza el 24 de agosto",
    campaign,
    primaryAction: { label: "Ver instrucciones", kind: "noop" },
  },
  campaignActive: {
    statusLabel: "Campaña activa",
    tone: "brand",
    title: "GlowUp España",
    description: "Mantén el ritmo: tienes hasta el 1 de septiembre para publicar los 8 vídeos.",
    deadline: "5 días restantes",
    progress: { value: 62.5, label: "5 de 8 vídeos", detail: "Próximo objetivo: 6 vídeos" },
    performance: {
      tiktokViews: "74,2 mil",
      instagramViews: "26,7 mil",
      referrals: "12",
      fixedEarnings: "150 €",
      bonusEarnings: "55 €",
      estimatedEarnings: "205 €",
      pendingVideos: 1,
    },
    recentVideos: videos.slice(0, 3),
    primaryAction: { label: "Subir un vídeo", kind: "upload" },
  },
  campaignReview: {
    statusLabel: "Campaña en revisión",
    tone: "neutral",
    title: "GlowUp ha cerrado sus publicaciones",
    description: "Estamos comprobando los vídeos y sus métricas para calcular el pago final.",
    meta: "Resultado previsto antes del 10 de septiembre",
    progress: { value: 100, label: "8 de 8 vídeos", detail: "Ya no puedes modificar los vídeos" },
    recentVideos: videos.slice(0, 4),
    primaryAction: { label: "Consultar vídeos", kind: "navigate", target: "videos" },
  },
  campaignFinalized: {
    statusLabel: "Campaña completada",
    tone: "positive",
    title: "¡GlowUp ha terminado!",
    description: "Tu pago ya está calculado y se encuentra pendiente de procesamiento.",
    meta: "8 vídeos aceptados · 126,8 mil visualizaciones",
    pendingPayment: pendingGlowUpPayment,
    primaryAction: { label: "Ver el pago", kind: "navigate", target: "payments" },
    secondaryAction: { label: "Ver vídeos", kind: "navigate", target: "videos" },
  },
  suspended: {
    statusLabel: "Cuenta pausada",
    tone: "warning",
    title: "Tu participación está suspendida temporalmente",
    description:
      "No puedes subir vídeos ni entrar en nuevas campañas mientras revisamos una incidencia con tu cuenta.",
    meta: "Revisión prevista antes del 5 de septiembre",
    primaryAction: { label: "Contactar con soporte", kind: "noop" },
    notice: {
      tone: "warning",
      title: "Tu histórico sigue disponible",
      description: "Puedes consultar tus vídeos y pagos anteriores con normalidad.",
    },
  },
  exited: {
    statusLabel: "Cuenta cerrada",
    tone: "neutral",
    title: "Tu colaboración con Proxus ha finalizado",
    description: "Puedes seguir consultando tus vídeos, documentos y pagos anteriores.",
    meta: "Cuenta cerrada el 12 de septiembre",
    primaryAction: { label: "Ver mis pagos", kind: "navigate", target: "payments" },
    secondaryAction: { label: "Ver mis vídeos", kind: "navigate", target: "videos" },
  },
} satisfies Record<CreatorScenario, CreatorHomePresentation>

export const creatorScenarioLabels = {
  applicationPending: "Solicitud pendiente",
  applicationRejected: "Solicitud rechazada",
  onboarding: "Onboarding",
  meetingPending: "Reunión pendiente",
  meetingScheduled: "Reunión reservada",
  meetingMissed: "Primera ausencia",
  trialPreparation: "Preparación del trial",
  trialWarming: "Calentamiento",
  trialPublishing: "Trial activo",
  trialReview: "Trial en revisión",
  trialNotPassed: "Trial no superado",
  waitingCampaign: "Esperando campaña",
  campaignScheduled: "Campaña programada",
  campaignActive: "Campaña activa",
  campaignReview: "Campaña en revisión",
  campaignFinalized: "Campaña finalizada",
  suspended: "Cuenta suspendida",
  exited: "Cuenta cerrada",
} satisfies Record<CreatorScenario, string>
