// @effect-diagnostics anyUnknownInErrorContext:off globalErrorInEffectCatch:off globalErrorInEffectFailure:off preferSchemaOverJson:off strictBooleanExpressions:off missingEffectError:off
import { SqlClient } from "effect/unstable/sql/SqlClient"
import { AgentStore, type AgentStoreError, type AgentStoreSnapshot, type RunCommit } from "@proxus/agent-harness/store"
import { ClaimLost, EntryAlreadyExists, EntryNotFound, InvalidCompaction, RunNotFound, SessionNotFound, VersionConflict } from "@proxus/agent-harness/errors"
import type { RunId, SessionEntryId, SessionId } from "@proxus/agent-harness/ids"
import type { JournalEvent, RunCheckpoint, RunRecord } from "@proxus/agent-harness/run"
import type { Session, SessionEntry } from "@proxus/agent-harness/session"
import { Effect, Layer } from "effect"

const parse = <A>(value: unknown): A => typeof value === "string" ? JSON.parse(value) as A : value as A
const stringify = (value: unknown): string => JSON.stringify(value)
const failure = (error: unknown): AgentStoreError => error as AgentStoreError
const terminal = ["Succeeded", "Failed", "Cancelled", "TimedOut", "BudgetExhausted", "Suspended"]

export const makeAgentStoreSql = Effect.gen(function*() {
  const sql = yield* SqlClient
  const tx = <A>(effect: Effect.Effect<A, AgentStoreError>) => sql.withTransaction(effect).pipe(Effect.mapError(failure))
  const run = (id: RunId) => sql<{ record: unknown }>`select record from agent_runs where id=${id}`.pipe(Effect.flatMap((rows) => rows[0] === undefined ? Effect.fail(new RunNotFound({ runId: id })) : Effect.succeed(parse<RunRecord>(rows[0].record))), Effect.mapError(failure))
  const session = (id: SessionId) => sql<{ record: unknown }>`select record from agent_sessions where id=${id}`.pipe(Effect.flatMap((rows) => rows[0] === undefined ? Effect.fail(new SessionNotFound({ sessionId: id })) : Effect.succeed(parse<Session>(rows[0].record))), Effect.mapError(failure))
  const entry = (id: SessionEntryId) => sql<{ entry: unknown }>`select entry from agent_session_entries where id=${id}`.pipe(Effect.map((rows) => rows[0] === undefined ? undefined : parse<SessionEntry>(rows[0].entry)), Effect.mapError(failure))
  const ancestry = (sessionId: SessionId, leaf: SessionEntryId | undefined): Effect.Effect<ReadonlyArray<SessionEntry>, AgentStoreError> => Effect.gen(function*() { const values: SessionEntry[]=[]; const seen=new Set<string>(); let current=leaf; while(current!==undefined){ if(seen.has(current)) return yield* new EntryNotFound({sessionId,entryId:current}); seen.add(current); const value=yield* entry(current); if(value===undefined||value.sessionId!==sessionId) return yield* new EntryNotFound({sessionId,entryId:current}); values.push(value); current=value.parentEntryId??undefined } return values.reverse() })
  const updateSession = (id: SessionId, expected: number, entries: ReadonlyArray<SessionEntry>, leaf: SessionEntryId) => Effect.gen(function*() { const old=yield* session(id); if(old.version!==expected) return yield* new VersionConflict({resource:"session",expectedVersion:expected,actualVersion:old.version}); for(const value of entries){ if(value.sessionId!==id) return yield* new EntryNotFound({sessionId:id,entryId:value.id}); if((yield* entry(value.id))!==undefined) return yield* new EntryAlreadyExists({entryId:value.id}); if(value.parentEntryId!==null&&(yield* entry(value.parentEntryId))===undefined) return yield* new EntryNotFound({sessionId:id,entryId:value.parentEntryId}); if(value.payload.type==="Compaction"){const compactedThroughEntryId=value.payload.compactedThroughEntryId;if(!(yield* ancestry(id,value.parentEntryId??undefined)).some((item)=>item.id===compactedThroughEntryId)) return yield* new InvalidCompaction({entryId:value.id,compactedThroughEntryId})}; yield* sql`insert into agent_session_entries(id,session_id,entry) values(${value.id},${id},${stringify(value)})`.pipe(Effect.mapError(failure)) } if((yield* entry(leaf))===undefined) return yield* new EntryNotFound({sessionId:id,entryId:leaf}); const next={...old,activeLeafId:leaf,version:old.version+1}; yield* sql`update agent_sessions set record=${stringify(next)} where id=${id}`.pipe(Effect.mapError(failure)); return next })
  const commit = (id: RunId, input: RunCommit) => tx(Effect.gen(function*(){ const old=yield* run(id); if(old.version!==input.expectedVersion) return yield* new VersionConflict({resource:"run",expectedVersion:input.expectedVersion,actualVersion:old.version}); if(input.session) yield* updateSession(input.session.entries[0]?.sessionId??old.sessionId!,input.session.expectedVersion,input.session.entries,input.session.activeLeafId); const rows=yield* sql<{ value: number }>`select coalesce(max(sequence),0)::int as value from agent_journal where run_id=${id}`.pipe(Effect.mapError(failure)); const count=rows[0]!.value; for(let index=0;index<input.events.length;index++){const event={...(old.parentRunId?{parentRunId:old.parentRunId}:{}),...(old.parentStepId?{parentStepId:old.parentStepId}:{}),...input.events[index]!,sequence:count+index+1}; yield* sql`insert into agent_journal(run_id,sequence,event) values(${id},${event.sequence},${stringify(event)})`.pipe(Effect.mapError(failure))} const next:RunRecord={...old,status:input.status??old.status,usage:input.usage??old.usage,context:input.context??old.context,...(input.output===undefined?{}:{output:input.output}),...(input.failure===undefined?{}:{failure:input.failure}),cancellationRequested:input.cancellationRequested??old.cancellationRequested,version:old.version+1}; yield* sql`update agent_runs set record=${stringify(next)}, status=${next.status} where id=${id}`.pipe(Effect.mapError(failure)); if(input.checkpoint){const checkpoint={...input.checkpoint,throughSequence:count+input.events.length,runVersion:next.version}; yield* sql`insert into agent_checkpoints(run_id,checkpoint) values(${id},${stringify(checkpoint)}) on conflict(run_id) do update set checkpoint=excluded.checkpoint`.pipe(Effect.mapError(failure))} return next }))
  return AgentStore.of({
    createRun:(value,event)=>tx(Effect.gen(function*(){yield* sql`insert into agent_runs(id,record,next_fencing_token) values(${value.id},${stringify(value)},1)`.pipe(Effect.mapError(failure)); yield* sql`insert into agent_journal(run_id,sequence,event) values(${value.id},1,${stringify({...event,sequence:1})})`.pipe(Effect.mapError(failure))})), getRun:run, commit,
    requestCancellation:(id,at)=>Effect.gen(function*(){const old=yield* run(id);if(!old.cancellationRequested)yield* commit(id,{expectedVersion:old.version,cancellationRequested:true,events:[{type:"CancellationRequested",at}]})}),
    awaitCancellation:(id):Effect.Effect<void,AgentStoreError>=>run(id).pipe(Effect.flatMap((value)=>value.cancellationRequested?Effect.void:Effect.sleep("50 millis").pipe(Effect.andThen(Effect.suspend(()=>run(id).pipe(Effect.flatMap((next)=>next.cancellationRequested?Effect.void:Effect.fail(new RunNotFound({runId:id}))))))))),
    events:(id,after=0)=>run(id).pipe(Effect.andThen(sql<{event:unknown}>`select event from agent_journal where run_id=${id} and sequence>${after} order by sequence`),Effect.map((rows)=>rows.map((row)=>parse<JournalEvent>(row.event))),Effect.mapError(failure)),
    checkpoint:(id)=>run(id).pipe(Effect.andThen(sql<{checkpoint:unknown}>`select checkpoint from agent_checkpoints where run_id=${id}`),Effect.map((rows)=>rows[0]===undefined?undefined:parse<RunCheckpoint>(rows[0].checkpoint)),Effect.mapError(failure)),
    claimNext:(ownerId,now,leaseMs)=>tx(Effect.gen(function*(){const rows=yield* sql<{id:RunId;record:unknown;nextFencingToken:number}>`select r.id,r.record,r.next_fencing_token as "nextFencingToken" from agent_runs r left join agent_run_claims c on c.run_id=r.id where r.status not in ${sql.in(terminal)} and (c.run_id is null or c.lease_expires_at<=${now}) order by r.created_at,r.id for update of r skip locked limit 1`.pipe(Effect.mapError(failure));const row=rows[0];if(!row)return undefined;const token=row.nextFencingToken;yield* sql`update agent_runs set next_fencing_token=${token+1} where id=${row.id}`.pipe(Effect.mapError(failure));yield* sql`insert into agent_run_claims(run_id,owner_id,fencing_token,lease_expires_at) values(${row.id},${ownerId},${token},${now+leaseMs}) on conflict(run_id) do update set owner_id=excluded.owner_id,fencing_token=excluded.fencing_token,lease_expires_at=excluded.lease_expires_at`.pipe(Effect.mapError(failure));return{run:parse<RunRecord>(row.record),ownerId,fencingToken:token,leaseExpiresAt:now+leaseMs}})),
    heartbeat:(id,ownerId,token,now,leaseMs)=>tx(Effect.gen(function*(){const rows=yield* sql<{runId:RunId}>`update agent_run_claims set lease_expires_at=${now+leaseMs} where run_id=${id} and owner_id=${ownerId} and fencing_token=${token} and lease_expires_at>${now} returning run_id as "runId"`.pipe(Effect.mapError(failure));if(rows.length!==1)return yield* new ClaimLost({runId:id,ownerId,fencingToken:token});return{run:yield*run(id),ownerId,fencingToken:token,leaseExpiresAt:now+leaseMs}})),
    releaseClaim:(id,ownerId,token)=>sql`delete from agent_run_claims where run_id=${id} and owner_id=${ownerId} and fencing_token=${token} returning run_id`.pipe(Effect.flatMap((rows)=>rows.length===1?Effect.void:Effect.fail(new ClaimLost({runId:id,ownerId,fencingToken:token}))),Effect.mapError(failure)),
    recoverOrphans:(now)=>sql<{runId:RunId}>`delete from agent_run_claims where lease_expires_at<=${now} returning run_id as "runId"`.pipe(Effect.map((rows)=>rows.map((row)=>row.runId)),Effect.mapError(failure)),
    replay:(after,limit=100)=>sql<{cursor:number;runId:RunId;event:unknown}>`select cursor,run_id as "runId",event from agent_journal where cursor>${after} order by cursor limit ${limit}`.pipe(Effect.map((rows)=>rows.map((row)=>({...row,event:parse<JournalEvent>(row.event)}))),Effect.mapError(failure)),
    createSession:(value)=>sql`insert into agent_sessions(id,record) values(${value.id},${stringify(value)})`.pipe(Effect.asVoid,Effect.mapError(failure)),getSession:session,
    appendSessionEntry:(value,version)=>tx(updateSession(value.sessionId,version,[value],value.id)),setActiveLeaf:(id,leaf,version)=>tx(updateSession(id,version,[],leaf)),sessionAncestry:(id,leaf)=>session(id).pipe(Effect.flatMap((value)=>ancestry(id,leaf??value.activeLeafId))),
    snapshot:Effect.gen(function*(){const runs=yield* sql<{record:unknown}>`select record from agent_runs order by id`;const sessions=yield* sql<{record:unknown}>`select record from agent_sessions order by id`;return{runs:yield*Effect.forEach(runs,({record})=>{const value=parse<RunRecord>(record);return Effect.all({run:Effect.succeed(value),events:sql<{event:unknown}>`select event from agent_journal where run_id=${value.id} order by sequence`.pipe(Effect.map((rows)=>rows.map((r)=>parse<JournalEvent>(r.event)))),checkpoint:sql<{checkpoint:unknown}>`select checkpoint from agent_checkpoints where run_id=${value.id}`.pipe(Effect.map((rows)=>rows[0]===undefined?undefined:parse<RunCheckpoint>(rows[0].checkpoint)))})}),sessions:yield*Effect.forEach(sessions,({record})=>{const value=parse<Session>(record);return sql<{entry:unknown}>`select entry from agent_session_entries where session_id=${value.id} order by created_at,id`.pipe(Effect.map((rows)=>({session:value,entries:rows.map((r)=>parse<SessionEntry>(r.entry))})))})} as AgentStoreSnapshot}).pipe(Effect.orDie)
  })
})

export const AgentStoreSqlLive = Layer.effect(AgentStore, makeAgentStoreSql)
