// @effect-diagnostics cryptoRandomUUID:off
import { createHmac } from "node:crypto"
import { describe, expect, it } from "vitest"
import { makeRunId, makeSessionId } from "@proxus/agent-harness/ids"
import type { PublicRunEvent } from "@proxus/agent-harness/transport"
import { ChatState, GoogleChatApp, type ChatMessage, type ChatStateSnapshot, type VerifiedChatEvent } from "./app.js"
import { SignedGoogleChatWebhook } from "./google-chat-adapter.js"
const address={tenant:"customers/acme",conversation:"spaces/eng",thread:"threads/42"}
const sessions=[makeSessionId("00000000-0000-4000-8000-000000000001")];const runs=[1,2,3].map(n=>makeRunId(`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`))
const fixture=(snapshot?:ChatStateSnapshot)=>{const posts:Array<{key:string;message:ChatMessage}>=[];const starts:Array<unknown>=[];const approvals:Array<unknown>=[];let s=0,r=0;const app=new GoogleChatApp({auth:{verify:req=>JSON.parse(req.body) as VerifiedChatEvent},output:{post:(_a,key,message)=>posts.push({key,message})},runs:{start:(...x)=>starts.push(x),resumeApproval:(...x)=>approvals.push(x)},state:new ChatState(snapshot),sessionId:()=>sessions[s++]!,runId:()=>runs[r++]!});return{app,posts,starts,approvals,state:(app as unknown as {deps:{state:ChatState}}).deps.state}}
const req=(deliveryId:string,text="investigate")=>({headers:{},body:JSON.stringify({deliveryId,address,actor:"users/alice",kind:"message",text})})
describe("Google Chat vertical",()=>{it("rejects unsigned requests",()=>{const auth=new SignedGoogleChatWebhook("secret");expect(()=>auth.verify({headers:{},body:"{}"})).toThrow()});it("verifies a signed webhook",()=>{const body=JSON.stringify({deliveryId:"d",tenant:"t",space:"s",thread:"th",actor:"a",type:"MESSAGE",text:"hi"});const sig=createHmac("sha256","secret").update(body).digest("hex");expect(new SignedGoogleChatWebhook("secret").verify({headers:{"x-proxus-signature":sig},body}).kind).toBe("message")});it("survives restart, deduplicates, queues at boundaries, projects child approval and posts final once",()=>{const first=fixture();expect(first.app.webhook(req("delivery-1")).status).toBe(200);first.app.webhook(req("delivery-1"));first.app.webhook(req("delivery-2","second"));expect(first.starts).toHaveLength(1);expect(first.posts).toHaveLength(2);const restarted=fixture(first.state.snapshot());restarted.app.webhook(req("delivery-1"));expect(restarted.posts).toHaveLength(0);restarted.app.turnBoundary(address,runs[0]!);expect(restarted.starts).toEqual([[sessions[0],runs[1],"second"]]);const events:PublicRunEvent[]=[{cursor:1,runId:runs[1]!,type:"ChildStarted",childRunId:runs[2]!,detail:"review"},{cursor:2,runId:runs[1]!,type:"ChildCompleted",childRunId:runs[2]!},{cursor:3,runId:runs[1]!,type:"ApprovalRequested",approvalId:"approval-1",summary:"Create PR?"},{cursor:4,runId:runs[1]!,type:"RunCompleted",output:"PR created safely."}];restarted.app.project(address,events);restarted.app.project(address,events);expect(restarted.posts.map(x=>x.key)).toEqual([`Progress:${runs[1]}:1`,`Progress:${runs[1]}:2`,`approval:approval-1`,`Final:${runs[1]}:4`]);const approval={deliveryId:"action-1",address,actor:"users/alice",kind:"approval" as const,approvalId:"approval-1",decision:"approved" as const};restarted.app.webhook({headers:{},body:JSON.stringify(approval)});restarted.app.webhook({headers:{},body:JSON.stringify(approval)});expect(restarted.approvals).toEqual([[runs[1],"approval-1","approved"]]);const again=fixture(restarted.state.snapshot());again.app.project(address,events);expect(again.posts).toHaveLength(0)})})
