// @effect-diagnostics anyUnknownInErrorContext:off strictEffectProvide:off strictBooleanExpressions:off
import { randomUUID } from "node:crypto"
import { deleteBackendServices,deleteRegionNetworkEndpointGroups,getBackendServices,getGlobalOperations,getRegionNetworkEndpointGroups,getRegionOperations,insertBackendServices,insertRegionNetworkEndpointGroups,patchBackendServices,type BackendService,type NetworkEndpointGroup,type Operation } from "@distilled.cloud/gcp/compute-v1"
import { Credentials,fromADC } from "@microagi/alchemy-gcp"
import { Duration,Effect,Layer } from "effect"
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient"
import type * as HttpClient from "effect/unstable/http/HttpClient"
import { ComputeBackendServiceProvider,ComputeClientError,ServerlessNegProvider,type ComputeBackendServiceClient,type ServerlessNegClient } from "./compute.ts"
export interface DistilledComputeOperations { getNeg(r:any):Effect.Effect<NetworkEndpointGroup,unknown>;insertNeg(r:any):Effect.Effect<Operation,unknown>;deleteNeg(r:any):Effect.Effect<Operation,unknown>;getBackend(r:any):Effect.Effect<BackendService,unknown>;insertBackend(r:any):Effect.Effect<Operation,unknown>;patchBackend(r:any):Effect.Effect<Operation,unknown>;deleteBackend(r:any):Effect.Effect<Operation,unknown>;regionOperation(r:any):Effect.Effect<Operation,unknown>;globalOperation(r:any):Effect.Effect<Operation,unknown>;readonly sleep:Effect.Effect<void> }
export interface ComputeLiveOptions {readonly project:string;readonly operations?:DistilledComputeOperations;readonly maxOperationPolls?:number}
const live=Layer.merge(fromADC(),FetchHttpClient.layer);const provide=<A,E>(e:Effect.Effect<A,E,Credentials|HttpClient.HttpClient>)=>e.pipe(Effect.provide(live))
const distilledComputeOperations:DistilledComputeOperations={getNeg:r=>provide(getRegionNetworkEndpointGroups(r)),insertNeg:r=>provide(insertRegionNetworkEndpointGroups(r)),deleteNeg:r=>provide(deleteRegionNetworkEndpointGroups(r)),getBackend:r=>provide(getBackendServices(r)),insertBackend:r=>provide(insertBackendServices(r)),patchBackend:r=>provide(patchBackendServices(r)),deleteBackend:r=>provide(deleteBackendServices(r)),regionOperation:r=>provide(getRegionOperations(r)),globalOperation:r=>provide(getGlobalOperations(r)),sleep:Effect.sleep(Duration.seconds(2))}
const code=(e:unknown):ComputeClientError["code"]=>{const t=typeof e==="object"&&e!==null&&"_tag"in e?String(e._tag):"";return t==="NotFound"?"not-found":t==="Forbidden"||t==="Unauthorized"?"forbidden":t==="Conflict"?"conflict":t==="BadRequest"?"invalid":"unknown"};const norm=(op:string)=>(e:unknown)=>e instanceof ComputeClientError?e:new ComputeClientError({operation:op,code:code(e)})
export const makeLiveComputeClients=({operations:o=distilledComputeOperations,maxOperationPolls=150}:ComputeLiveOptions):{neg:ServerlessNegClient;backend:ComputeBackendServiceClient}=>{const map=<A>(op:string,e:Effect.Effect<A,unknown>)=>e.pipe(Effect.mapError(norm(op)));const awaitOp=(scope:"region"|"global",project:string,region:string|undefined,first:Operation,op:string,n=0):Effect.Effect<void,ComputeClientError>=>first.status==="DONE"?(first.error?Effect.fail(new ComputeClientError({operation:op,code:"operation-failed"})):Effect.void):!first.name?Effect.fail(new ComputeClientError({operation:op,code:"operation-failed"})):n>=maxOperationPolls?Effect.fail(new ComputeClientError({operation:op,code:"timeout"})):o.sleep.pipe(Effect.flatMap(()=>map(op,scope==="region"?o.regionOperation({project,region,operation:first.name}):o.globalOperation({project,operation:first.name}))),Effect.flatMap(x=>awaitOp(scope,project,region,x,op,n+1)));const id=()=>randomUUID();return {neg:{get:(project,region,name)=>map("get-neg",o.getNeg({project,region,networkEndpointGroup:name})),create:(project,region,body)=>map("insert-neg",o.insertNeg({project,region,requestId:id(),body})).pipe(Effect.flatMap(x=>awaitOp("region",project,region,x,"insert-neg")),Effect.flatMap(()=>map("get-after-insert-neg",o.getNeg({project,region,networkEndpointGroup:body.name!})))),delete:(project,region,name)=>map("delete-neg",o.deleteNeg({project,region,networkEndpointGroup:name,requestId:id()})).pipe(Effect.flatMap(x=>awaitOp("region",project,region,x,"delete-neg")))},backend:{get:(project,name)=>map("get-backend",o.getBackend({project,backendService:name})),create:(project,body)=>map("insert-backend",o.insertBackend({project,requestId:id(),body})).pipe(Effect.flatMap(x=>awaitOp("global",project,undefined,x,"insert-backend")),Effect.flatMap(()=>map("get-after-insert-backend",o.getBackend({project,backendService:body.name!})))),patch:(project,name,body)=>map("patch-backend",o.patchBackend({project,backendService:name,requestId:id(),body})).pipe(Effect.flatMap(x=>awaitOp("global",project,undefined,x,"patch-backend")),Effect.flatMap(()=>map("get-after-patch-backend",o.getBackend({project,backendService:name})))),delete:(project,name)=>map("delete-backend",o.deleteBackend({project,backendService:name,requestId:id()})).pipe(Effect.flatMap(x=>awaitOp("global",project,undefined,x,"delete-backend")))}}}
export const computeLiveLayer=(options:ComputeLiveOptions)=>{const c=makeLiveComputeClients(options);return Layer.merge(ServerlessNegProvider(c.neg),ComputeBackendServiceProvider(c.backend))}
