// @effect-diagnostics anyUnknownInErrorContext:off strictEffectProvide:off strictBooleanExpressions:off
import { randomUUID } from "node:crypto"
import { deleteGlobalAddresses,deleteGlobalForwardingRules,deleteSslCertificates,deleteTargetHttpsProxies,deleteUrlMaps,getGlobalAddresses,getGlobalForwardingRules,getGlobalOperations,getSslCertificates,getTargetHttpsProxies,getUrlMaps,insertGlobalAddresses,insertGlobalForwardingRules,insertSslCertificates,insertTargetHttpsProxies,insertUrlMaps,patchGlobalForwardingRules,patchTargetHttpsProxies,patchUrlMaps,type Address,type ForwardingRule,type Operation,type SslCertificate,type TargetHttpsProxy,type UrlMap } from "@distilled.cloud/gcp/compute-v1"
import { Credentials,fromADC } from "@microagi/alchemy-gcp"
import { Duration,Effect,Layer } from "effect"
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient"
import type * as HttpClient from "effect/unstable/http/HttpClient"
import { EdgeClientError,edgeProviderLayer,type EdgeClient } from "./edge.ts"
export interface DistilledEdgeOperations {get(kind:string,r:any):Effect.Effect<any,unknown>;insert(kind:string,r:any):Effect.Effect<Operation,unknown>;patch(kind:string,r:any):Effect.Effect<Operation,unknown>;delete(kind:string,r:any):Effect.Effect<Operation,unknown>;operation(r:any):Effect.Effect<Operation,unknown>;readonly sleep:Effect.Effect<void>}
const live=Layer.merge(fromADC(),FetchHttpClient.layer);const provide=<A,E>(e:Effect.Effect<A,E,Credentials|HttpClient.HttpClient>)=>e.pipe(Effect.provide(live))
const table:any={address:{get:getGlobalAddresses,insert:insertGlobalAddresses,delete:deleteGlobalAddresses,key:"address"},certificate:{get:getSslCertificates,insert:insertSslCertificates,delete:deleteSslCertificates,key:"sslCertificate"},urlMap:{get:getUrlMaps,insert:insertUrlMaps,patch:patchUrlMaps,delete:deleteUrlMaps,key:"urlMap"},proxy:{get:getTargetHttpsProxies,insert:insertTargetHttpsProxies,patch:patchTargetHttpsProxies,delete:deleteTargetHttpsProxies,key:"targetHttpsProxy"},forwardingRule:{get:getGlobalForwardingRules,insert:insertGlobalForwardingRules,patch:patchGlobalForwardingRules,delete:deleteGlobalForwardingRules,key:"forwardingRule"}}
const distilledEdgeOperations:DistilledEdgeOperations={get:(k,r)=>provide(table[k].get(r)),insert:(k,r)=>provide(table[k].insert(r)),patch:(k,r)=>provide(table[k].patch(r)),delete:(k,r)=>provide(table[k].delete(r)),operation:r=>provide(getGlobalOperations(r)),sleep:Effect.sleep(Duration.seconds(2))}
export interface EdgeLiveOptions {readonly project:string;readonly operations?:DistilledEdgeOperations;readonly maxOperationPolls?:number}
const code=(e:unknown):EdgeClientError["code"]=>{const t=typeof e==="object"&&e!==null&&"_tag"in e?String(e._tag):"";return t==="NotFound"?"not-found":t==="Forbidden"||t==="Unauthorized"?"forbidden":t==="Conflict"?"conflict":t==="BadRequest"?"invalid":"unknown"}
export const makeLiveEdgeClients=({operations:o=distilledEdgeOperations,maxOperationPolls=150}:EdgeLiveOptions)=>{const map=<A>(op:string,e:Effect.Effect<A,unknown>)=>e.pipe(Effect.mapError(e=>e instanceof EdgeClientError?e:new EdgeClientError({operation:op,code:code(e)})));const wait=(project:string,x:Operation,op:string,n=0):Effect.Effect<void,EdgeClientError>=>x.status==="DONE"?(x.error?Effect.fail(new EdgeClientError({operation:op,code:"operation-failed"})):Effect.void):!x.name?Effect.fail(new EdgeClientError({operation:op,code:"operation-failed"})):n>=maxOperationPolls?Effect.fail(new EdgeClientError({operation:op,code:"timeout"})):o.sleep.pipe(Effect.flatMap(()=>map(op,o.operation({project,operation:x.name}))),Effect.flatMap(y=>wait(project,y,op,n+1)));const make=<A>(kind:string,key:string,canPatch:boolean):EdgeClient<A>=>{const request=(project:string,name:string)=>({project,[key]:name});const mutate=(project:string,name:string,verb:"insert"|"patch",body:A)=>map(`${verb}-${kind}`,o[verb](kind,{...request(project,name),requestId:randomUUID(),body})).pipe(Effect.flatMap(x=>wait(project,x,`${verb}-${kind}`)),Effect.flatMap(()=>map(`get-after-${verb}-${kind}`,o.get(kind,request(project,name)))));return {get:(p,n)=>map(`get-${kind}`,o.get(kind,request(p,n))),create:(p,b)=>mutate(p,(b as any).name,"insert",b),...(canPatch?{patch:(p:string,n:string,b:A)=>mutate(p,n,"patch",b)}:{}),delete:(p,n)=>map(`delete-${kind}`,o.delete(kind,{...request(p,n),requestId:randomUUID()})).pipe(Effect.flatMap(x=>wait(p,x,`delete-${kind}`)))}};return {address:make<Address>("address","address",false),certificate:make<SslCertificate>("certificate","sslCertificate",false),urlMap:make<UrlMap>("urlMap","urlMap",true),proxy:make<TargetHttpsProxy>("proxy","targetHttpsProxy",true),forwardingRule:make<ForwardingRule>("forwardingRule","forwardingRule",true)}}
export const edgeLiveLayer=(options:EdgeLiveOptions)=>edgeProviderLayer(makeLiveEdgeClients(options))
