// @effect-diagnostics asyncFunction:off strictBooleanExpressions:off anyUnknownInErrorContext:off
import { Unowned } from "alchemy/AdoptPolicy"
import type { ScopedPlanStatusSession } from "alchemy/Cli/Cli"
import { Effect } from "effect"
import { describe, expect, it } from "vitest"
import { makeStorageObjectProviderService, StorageObjectClientError, type StorageObjectClient, type StorageObjectMetadata } from "./storage-object.ts"
const run = Effect.runPromise
const base = { id: "asset", fqn: "prod/asset", instanceId: "i", session: { note: () => Effect.void } as unknown as ScopedPlanStatusSession, bindings: [] }
const props = { bucket: "web", name: "assets/app.ts", source: { path: "/build/app.ts", sha256: "abc", size: 3 }, contentType: "text/javascript", cacheControl: "public,max-age=31536000,immutable" }
const fake = () => { let value: StorageObjectMetadata | undefined; const calls: string[] = []; const client: StorageObjectClient = { assertOwnedBucket: (bucket) => bucket === "web" ? Effect.void : Effect.fail(new StorageObjectClientError({ operation: "bucket", code: "foreign-bucket" })), get: () => value ? Effect.succeed(value) : Effect.fail(new StorageObjectClientError({ operation: "get", code: "not-found" })), list: () => Effect.succeed(value ? [value] : []), upload: (p, generation) => { calls.push(`upload:${generation}`); value = { bucket: p.bucket, name: p.name, sourceSha256: p.source.sha256, contentType: p.contentType, cacheControl: p.cacheControl, generation: String(Number(generation) + 1), etag: "etag" }; return Effect.succeed(value) }, delete: (_b, _n, generation) => { calls.push(`delete:${generation}`); value = undefined; return Effect.void } }; return { client, calls, set: (v: StorageObjectMetadata) => { value = v } } }
describe("StorageObject provider", () => {
  it("creates, reads, lists, updates and generation-safe deletes without storing content", async () => { const f = fake(); const p = makeStorageObjectProviderService(f.client); const output = await run(p.reconcile({ ...base, news: props, olds: undefined, output: undefined })); expect(f.calls).toEqual(["upload:0"]); expect(output).not.toHaveProperty("content"); expect(await run(p.read!({ ...base, olds: props, output }))).toEqual(output); expect(await run(p.list())).toHaveLength(1); const changed = { ...props, source: { ...props.source, sha256: "def" } }; const updated = await run(p.reconcile({ ...base, news: changed, olds: props, output })); expect(f.calls.at(-1)).toBe("upload:1"); await run(p.delete({ ...base, olds: changed, output: updated })); expect(f.calls.at(-1)).toBe("delete:2") })
  it("adopts only exact descriptors and protects foreign objects and buckets", async () => { const f = fake(); f.set({ bucket: "web", name: props.name, sourceSha256: "abc", contentType: props.contentType, cacheControl: props.cacheControl, generation: "7", etag: "e" }); const p = makeStorageObjectProviderService(f.client); expect(await run(p.read!({ ...base, olds: props, output: undefined }))).toMatchObject({ generation: "7" }); f.set({ bucket: "web", name: props.name, sourceSha256: "other", generation: "8", etag: "x" }); expect(Unowned.is(await run(p.read!({ ...base, olds: props, output: undefined })))).toBe(true); await expect(run(p.reconcile({ ...base, news: props, olds: undefined, output: undefined }))).rejects.toMatchObject({ code: "conflict" }); await expect(run(p.reconcile({ ...base, news: { ...props, bucket: "foreign" }, olds: undefined, output: undefined }))).rejects.toMatchObject({ code: "foreign-bucket" }) })
  it("diff is descriptor-only and replaces physical identity", async () => { const p = makeStorageObjectProviderService(fake().client); expect(await run(p.diff!({ ...base, olds: props, news: { ...props, source: { ...props.source, sha256: "new" } }, output: undefined, oldBindings: [], newBindings: [] }))).toBeUndefined(); expect(await run(p.diff!({ ...base, olds: props, news: { ...props, name: "other" }, output: undefined, oldBindings: [], newBindings: [] }))).toEqual({ action: "replace" }) })
})
