// @effect-diagnostics asyncFunction:off
import { Effect } from "effect"
import { describe, expect, it } from "vitest"
import { makeLiveStorageObjectClient, type StorageObjectHttpResponse, type StorageObjectRequestInit } from "./storage-object-live.ts"
const response = (status: number, value: unknown): StorageObjectHttpResponse => ({ status, json: async () => value })
describe("StorageObject live adapter", () => {
  it("reads source only for media upload and sends metadata with a generation precondition", async () => { const calls: Array<{ url: string; init: StorageObjectRequestInit }> = []; let reads = 0; const client = makeLiveStorageObjectClient({ project: "p", projectNumber: "123", buckets: ["web"], accessToken: () => Effect.succeed("token"), readSource: async () => { reads++; return new Uint8Array([1, 2, 3]) }, request: async (url, init) => { calls.push({ url, init }); if (url.endsWith("/b/web")) return response(200, { projectNumber: "123" }); return response(200, { name: "app.ts", generation: "9", etag: "etag", contentType: "text/javascript", cacheControl: "public", metadata: { "proxus-source-sha256": "abc" } }) } }); await Effect.runPromise(client.assertOwnedBucket("web")); await Effect.runPromise(client.get("web", "app.ts")); expect(reads).toBe(0); const value = await Effect.runPromise(client.upload({ bucket: "web", name: "app.ts", source: { path: "/asset", sha256: "abc", size: 3 }, contentType: "text/javascript", cacheControl: "public" }, "8")); expect(reads).toBe(1); expect(value).toMatchObject({ generation: "9", etag: "etag", sourceSha256: "abc" }); expect(calls.at(-1)?.url).toContain("uploadType=media"); expect(calls.at(-1)?.url).toContain("ifGenerationMatch=8"); expect(calls.at(-1)?.init.headers).toMatchObject({ "x-goog-meta-proxus-source-sha256": "abc" }) })
  it("fails closed before object access for unconfigured or foreign buckets", async () => { let requests = 0; const base = { project: "p", projectNumber: "123", buckets: ["web"], accessToken: () => Effect.succeed("token"), request: async () => { requests++; return response(200, { projectNumber: "999" }) } }; await expect(Effect.runPromise(makeLiveStorageObjectClient(base).assertOwnedBucket("web"))).rejects.toMatchObject({ code: "foreign-bucket" }); await expect(Effect.runPromise(makeLiveStorageObjectClient(base).assertOwnedBucket("other"))).rejects.toMatchObject({ code: "foreign-bucket" }); expect(requests).toBe(1) })
})
